[build]
builder = "NIXPACKS"
buildCommand = "export PATH=/opt/venv/bin:$PATH && npm ci && npm run build"

[deploy]
startCommand = "export PATH=/opt/venv/bin:$PATH && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
